name: publish chart

on:
  push:
    branches:
      - main

jobs:

  publish:

    runs-on: ubuntu-22.04

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.0

      - name: Setup Chartmusem
        run: |
          helm plugin install https://github.com/chartmuseum/helm-push
          helm repo add chartmuseum https://chartmuseum.production.cafemedia.com --username pull --password ${{ secrets.CHARTMUSEUM_PASSWORD }}

      - name: Publish to Chartmuseum
        run: |
          ALL_CHANGED_CHARTS="$(ct list-changed --target-branch=${{ github.event.repository.default_branch }} --since=HEAD~1)"
          echo "$ALL_CHANGED_CHARTS" | while IFS= read -r chart ; do
            helm cm-push ${chart} chartmuseum
          done